import Section from "@/components/common/Section";
import Banner from "@/components/home/Banner";
import Header from "@/components/layout/Header";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Certivale | Certificado Digital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <Section id="inicio">
          <Banner />
        </Section>
      </main>
    </>
  );
}
