import Section from "@/components/common/Section";
import Banner from "@/components/home/Banner";
import History from "@/components/home/History";
import Online from "@/components/home/Online";
import Products from "@/components/home/Products";
import Testimonials from "@/components/home/Testimonials";
import Header from "@/components/layout/Header";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Certivale | Certificado Digital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <Section id="inicio">
          <Banner />
        </Section>

        <Section id="produtos" pt="200 96" pb="120 80">
          <Products />
        </Section>

        <Section id="online" pt="96 80" pb="96 80" style={{ backgroundColor: 'rgb(var(--deep-blue))' }}>
          <Online />
        </Section>

        <Section id="sobre-nos" pt="120 80" pb="64 80">
          <History />
        </Section>

        <Section id="testimonials" pt="96 72" pb="104 72">
          <Testimonials />
        </Section>
      </main>
    </>
  );
}
